first_app/urls.py
from first_app import views
from django.urls import path
app_name = 'first_app'

urlpatterns = [
    path('login/',views.login_view,name= "login"),
    path('success/',views.success_view,name='success'),
    path('', views.index, name='index'),
    path('login/',views.form_view,name = "form_view"),
    path('register/',views.register,name='register'),
    path('extended/',views.extended,name='extended'),
    path('loginn/',views.user_login,name="user_login"),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name ="special"),
    path('list/',views.SchoolList.as_view(),name = "list"),
    path("list/<int:pk>/",views.SchoolDetail.as_view(),name ='detail'),
    path("update/list/<int:pk>/",views.SchoolUpdate.as_view(),name ='update'),
    path('create/',views.SchoolCreate.as_view(),name = "create"),
    path("delete/<int:pk>/",views.SchoolDelete.as_view(),name ='delete'),



]

first_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from first_app import views
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('first_app/', include('first_app.urls',namespace = "first_app")),
    path('success/',views.success_view,name='success'),
    path('test/',views.TestView.as_view(),name = 'test')
]

first_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
#Create your models here.
class Topic(models.Model):
    topic_name = models.CharField(max_length = 256,unique = True)
def __str__(self):
    return self.topic_name

class WebPage(models.Model):
    topic_ref = models.ForeignKey(Topic,on_delete=models.CASCADE )
    name = models.CharField(max_length = 256,unique = True)
    url = models.URLField(unique = True)
def __str__(self):
    return self.name


class AccessRecord(models.Model):
    name_rec = models.ForeignKey(WebPage,on_delete=models.CASCADE)
    date = models.DateField()

def __str__(self):
    return str(self.date)

class Login(models.Model):
    name = models.CharField(max_length = 256)
    email = models.EmailField()
    password = models.CharField(max_length = 12)
def __str__(self):
    return self.name

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    #additional

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to = "Profile_pic",blank = True)

def __str__(self):
    return self.user.username

class School(models.Model):
    name = models.CharField(max_length = 256)
    principal = models.CharField(max_length=256)
    location = models.CharField( max_length=256)
    def get_absolute_url(self):
        return reverse('first_app:detail',kwargs={'pk':self.pk})
def __str__(self):
    return self.name
class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School,on_delete=models.CASCADE,related_name = 'students')
def __str__(self):
    return self.name

first_app/forms.py
from django import forms
from django.core import validators
from first_app.models import Login,UserProfileInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput)
    class Meta():
        model = Login
        fields ="__all__"
class FormName(forms.Form):
    def need_start_z(value):
        if value[0].lower()!='z':
            raise forms. ValidationError("Name needs to strat with z")
    name = forms.CharField(validators=[need_start_z])
    email = forms.EmailField()
    verify_email = forms.EmailField(label="Please confirm your email")
    text = forms.CharField(widget = forms.Textarea)
    botcatcher = forms.CharField(required=False,widget = forms.HiddenInput,validators=[validators.MaxLengthValidator(0)])
    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data["email"]
        vemail = all_clean_data["verify_email"]
        if email != vemail:
            raise forms.ValidationError("Emails donot match!")
class UserFormm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput)
    class Meta():
        model = User
        fields = ('username','email','password')
class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model  = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from first_app.models import AccessRecord,Topic,WebPage,Login,School
from first_app import forms
from first_app.forms import UserForm,UserFormm,UserProfileInfoForm
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse,reverse_lazy
from django.http import HttpResponse,HttpResponseRedirect
from  django.contrib.auth.decorators import login_required
from . import models
from django.views.generic import TemplateView,View,ListView,DetailView,CreateView,UpdateView,DeleteView

# Create your views here.
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('success'))
@login_required
def special(request):
    return HttpResponse("Yadd atey ho bohat...login kr to ateyy...")

def index(request):
    acc_recrd = AccessRecord.objects.order_by("date")
    date_dict = {"access_records":acc_recrd}
    pass
    return render(request, 'first_app/index.html', context = date_dict)
def form_view(request):
    form = forms.FormName()
    if (request.method == "POST"):
        form = forms.FormName(request.POST)
        if(form.is_valid()):
            print("Name is "+form.cleaned_data["name"]),
            print("Email is "+form.cleaned_data["email"]),
            print("Text is "+form.cleaned_data["text"]),
    return render(request, 'first_app/form.html', {"form":form})

def login_view(request):
    form_login = forms.UserForm()
    if(request.method == "POST"):
        form_login = forms.UserForm(request.POST)
        if form_login.is_valid():
            form_login.save(commit=True)

    return render(request,'first_app/login.html',{"login_form":form_login})
def success_view(request):
    context_dict = {"body":"hello man we are very happy to help you","number":100}
    return render(request,'first_app/success.html',context=context_dict)
def extended(request):
    return render(request,'first_app/extended.html')
def register(request):
    registered = False
    if (request.method == 'POST'):
        user_form = UserFormm(data = request.POST)
        profile_form = UserProfileInfoForm(data = request.POST)
        if( user_form.is_valid() and profile_form.is_valid()):
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user # representing one to one relationship
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserFormm()
        profile_form = UserProfileInfoForm()
    return render(request,'first_app/registration.html',{'user_form':user_form,'profile_info':profile_form,'registered':registered})
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('success'))
            else:
                return HttpResponse("NO user found")
        else:
            print("Invalid creds")
            print("username is {} an password is {}".format(username,password))
    else:
        return render(request,'first_app/loginn.html')
class TestView(TemplateView):
    template_name = 'first_app/test.html'
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['sqlinject'] = "Injected Successfully"
        return context
class SchoolList(ListView):
    model = models.School#context = school_list
    context_object_name = "school_list"
    template_name='first_app/first_app_list.html'

class SchoolDetail(DetailView):
    model =models.School
    template_name = 'first_app/first_app_detail.html'
    context_object_name = "school_detail"
class SchoolCreate(CreateView):
    model = models.School
    fields = ('name','principal','location')

class SchoolUpdate(UpdateView):
    fields= ('name','principal')
    model = models.School

class SchoolDelete(DeleteView):
    model = models.School
    success_url = reverse_lazy('first_app:list')

first_app/templates/first_app/first_app_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'first_app:list'%}"> List of Schools <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'first_app:register'%}">Register</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="{% url 'admin:index' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          admin
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      {% if user.is_authenticated %}
      <li> <a class='navbar-link' href="{% url 'first_app:logout' %}">Logout</a></li>
      {% else %}
      <li> <a class='navbar-link' href="{% url 'first_app:user_login' %}">Login</a></li>
      {% endif %}
      <li class="nav-item">
        <a class="nav-link " href="#" ></a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

<a href="{% url 'first_app:extended'%}">Check here for inheritence</a>
    {% block body_block %}
    {% endblock %}

  </body>
</html>

first_app/templates/first_app/first_app_detail.html
{% extends 'first_app/first_app_base.html' %}
{% block body_block %}
<div class="jumbotron">
<h1>School Details Available</h1>
  <p>Name of School is {{school_detail.name}}</p>
  <p>Principal is {{school_detail.principal}}</p>
  <p>location is {{school_detail.location}}</p>
  <h3>Students:</h3>
  <br>
  {% for student in student_detail.students.all %}
  <p>Name is {{student.name}}</p>
  <p>Name is {{student.age}}</p>
  <p>Name is {{student.school}}</p>
</div>
{% endblock %}

first_app/templates/first_app/first_app_list.html
{% extends 'first_app/first_app_base.html' %}
{% block body_block %}

<h1>Welcome to List of All the Schools`</h1>
{% for school in school_list %}
<ol>
  <a href="{{school.id}}">{{ school.name }}</a>


</ol>
{% endfor %}


{% endblock %}

templates/first_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'first_app:index'%}"> Index <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'first_app:register'%}">Register</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="{% url 'admin:index' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          admin
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      {% if user.is_authenticated %}
      <li> <a class='navbar-link' href="{% url 'first_app:logout' %}">Logout</a></li>
      {% else %}
      <li> <a class='navbar-link' href="{% url 'first_app:user_login' %}">Login</a></li>
      {% endif %}
      <li class="nav-item">
        <a class="nav-link " href="#" ></a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

<a href="{% url 'first_app:extended'%}">Check here for inheritence</a>
    {% block body_block %}
    {% endblock %}

  </body>
</html>

templates/first_app/extended.html
<!DOCTYPE html>
{% extends 'first_app/base.html'%}
{% block body_block %}
<h1>Welcome to extended page</h1>
{% endblock %}

templates/first_app/first_app_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'first_app:list'%}"> List of Schools <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'first_app:register'%}">Register</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="{% url 'admin:index' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          admin
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      {% if user.is_authenticated %}
      <li> <a class='navbar-link' href="{% url 'first_app:logout' %}">Logout</a></li>
      {% else %}
      <li> <a class='navbar-link' href="{% url 'first_app:user_login' %}">Login</a></li>
      {% endif %}
      <li class="nav-item">
        <a class="nav-link " href="#" ></a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

<a href="{% url 'first_app:extended'%}">Check here for inheritence</a>
    {% block body_block %}
    {% endblock %}

  </body>
</html>

templates/first_app/first_app_detail.html
{% extends 'first_app/first_app_base.html' %}
{% block body_block %}
<div class="jumbotron">
<h1>School Details Available</h1>
  <p>Name of School is {{school_detail.name}}</p>
  <p>Principal is {{school_detail.principal}}</p>
  <p>location is {{school_detail.location}}</p>
  <h3>Students:</h3>
  {% for student in school_detail.students.all %}
  <p>Name is {{ student.name }}</p>
  <p>Age is {{ student.age }}</p>
  {% endfor %}
    <p><a href="{% url 'first_app:update' pk=school_detail.pk %}" class="btn btn-warning">Update</a></p>
</div>


{% endblock %}

templates/first_app/first_app_list.html
{% extends 'first_app/first_app_base.html' %}
{% block body_block %}

<h1>Welcome to List of All the Schools`</h1>
{% for school in school_list %}
<ol>
  <a href="{{ school.id }}">{{ school.name }}</a>
</ol>
{% endfor %}
{% endblock %}

templates/first_app/form.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to my form</h1>

    <div class="container">

      <form  method="post">
          {{ form.as_p }}
          {% csrf_token %}
          <input type="submit" class="btn btn-primary" value="Submit">
        
    </form>
      </div>

  </body>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</html>

templates/first_app/index.html
<!DOCTYPE html>
{% extends 'first_app/base.html'%}
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <link  rel="stylesheet" href="{% static "css/style.css" %}"/>
    <meta charset="utf-8">
    <title>First App</title>
  </head>
  <body>
    <h1>Welcome Back my boys Hope you have enjoyed it</h1>
    {{ testData }}
    <img src="{% static "images/background.jfif" %}",alt="A smooth"/>
    <div class="border_class">
      {% if access_records %}
      <table>
        <thead>
          <th>Site Name</th>
          <th> Url Link</th>
        </thead>
        <tbody>
            {% for acc in access_records %}
            <tr>
              <td>
              {{acc.name_rec}}
            </td>
            <td>
              {{acc.date}}
            </td>
            </tr>

            {% endfor %}

        </tbody>




      </table>
      {% else %}
      <p> No Access Record Found </p>
      {% endif  %}




     </div>
     <a href="{% url 'first_app:extended'%}">Check here for inheritence</a>


  </body>
</html>

templates/first_app/login.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="container">
      <form  method="POST">
      {{ login_form.as_p }}
      {% csrf_token %}
      <input type="submit" class="btn btn-primary" value="Submit">
        <a href="{% url 'first_app:success' %}">Click here to finish!</a>
      </form>

    </div>

  </body>
</html>

templates/first_app/loginn.html
{% extends 'first_app/base.html'%}
{% block body_block %}

<div class="jumbotron">
  <h1>Please Login here</h1>
  <form  action="{% url 'first_app:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Enter your Username</label>
    <input type="text" name="username" placeholder="Enter Username">
    <br>
    <label for="password">Password</label>
    <input type="password" name="password" >
    <input type="submit" class="btn btn-secondary" value="Login">
    <br>

  </form>
</div>


{% endblock %}

templates/first_app/registration.html
{% extends 'first_app/base.html'%}
{% load static  %}
{% block body_block %}
<div class="jumbotron">
  {% if registered %}
  <h1>Thankyou for registeration </h1>
  {% else %}
  <h3>You can Register here... </h3>
  <h5>Fill the form out!</h5>
  <form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_info.as_p }}
    <input type="submit" class="btn btn-primary" value="Register">

  </form>


  {% endif %}

</div>




{% endblock %}

templates/first_app/school_confirm_delete.html
{% extends 'first_app/first_app_base.html' %}
{% block body_block %}
<h1>Delete {{ school.name }}?</h1>
<form  method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Delete">
  <p><a class="btn btn-danger" href="{% url 'first_app:detail' pk=school.pk%}">Cancel</a></p>

</form>

{% endblock %}

templates/first_app/school_form.html
{% extends 'first_app/base.html'%}
{% block body_block %}
<div class="jumbotron">
  <div class="container">
    {% if not form.instance.pk %}
    <h1>Create School</h1>
    {% else %}
    <h2>Update School</h2>


    {% endif %}
  </div>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class ='btn btn-primary' value="Submit">
  </form>

</div>
{% endblock %}

templates/first_app/success.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}



  {% block body_block %}
    <h1>Task completed successfully</h1>
    <h1>{{ body|cut:"hello" }}</h1>
    <h1>{{ number }}</h1>
    <i class="material-icons">done</i>
    {% endblock %}

templates/first_app/test.html
{% extends 'first_app/base.html' %}
{% block body_block %}
<h1>This is the testing page</h1>
{{ sqlinject }}

{% endblock %}